#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: et sts=4 sw=4

set -eu

HOME_DEVICE="/dev/disk/by-partsets/shared/home"
HOME_MOUNTPOINT="/home"
ROOTFS_DEVICE="/dev/disk/by-partsets/self/rootfs"
ROOTFS_MOUNTPOINT="/mnt"
VAR_DEVICE="/dev/disk/by-partsets/self/var"
VAR_MOUNTPOINT="/tmp/var"
SDDM_CONF_FILE="/etc/sddm.conf.d/zzzz-steamos-convert-home-to-btrfs.conf"
LOGFILE="/var/log/steamos-btrfs.log"

if [[ -f /etc/default/steamos-btrfs ]]
then
    source /etc/default/steamos-btrfs
fi
HOME_CONVERT_OPTS="${STEAMOS_BTRFS_HOME_CONVERT_OPTS:--L --uuid copy}"
HOME_MOUNT_OPTS="${STEAMOS_BTRFS_HOME_MOUNT_OPTS:-defaults,nofail,x-systemd.growfs,noatime,lazytime,compress-force=zstd,space_cache=v2,autodefrag}"
HOME_MOUNT_SUBVOL="${STEAMOS_BTRFS_HOME_MOUNT_SUBVOL:-@}"

cmd() {
    echo '[$]' "${@@Q}" >&2
    "$@"
}

mask_service() {
    cmd systemctl --no-block mask steamos-convert-home-to-btrfs.service || true
}
clear_sddm_conf() {
    cmd rm -f "$SDDM_CONF_FILE" || true
}
onexit=(clear_sddm_conf mask_service)
exit_handler() {
    for func in "${onexit[@]}"
    do
        "$func" || true
    done
    onexit=()
}
trap exit_handler SIGINT SIGQUIT SIGTERM ERR EXIT

if [[ "$(blkid -o value -s TYPE "$HOME_DEVICE")" != "ext4" ]]
then
    echo "(100%) Removing sddm configuration '$SDDM_CONF_FILE'."
    exit_handler
    echo "(100%) $HOME_MOUNTPOINT is already formatted as btrfs"
    systemd-notify --ready --status="$HOME_MOUNTPOINT is already formatted as btrfs"
    exit 0
fi

exit_reboot_error() {
    echo "(100%) Error encountered. Rebooting in 120 seconds..."
    echo "(100%) Please check '${LOGFILE}' and report any issues."
    # don't remove the sddm override too early, sddm might not be started yet
    sleep 10
    clear_sddm_conf
    mask_service
    sleep 110
    cmd systemctl reboot
}

exit_log() {
    if ! [[ -s "$LOGFILE" ]]
    then
        return
    fi
    if [[ "$(blkid -o value -s TYPE "$HOME_DEVICE")" != "btrfs" ]]
    then
        if ! cmd mount "$HOME_DEVICE" "$HOME_MOUNTPOINT"
        then
            return
        fi
        LOGFILE_OFFLOAD="${HOME_MOUNTPOINT}/.steamos/offload${LOGFILE}"
    else
        if ! cmd mount -o "${HOME_MOUNT_OPTS}" "$HOME_DEVICE" "$HOME_MOUNTPOINT"
        then
            return
        fi
        if cmd btrfs subvolume show "${HOME_MOUNTPOINT}/${HOME_MOUNT_SUBVOL}" &>/dev/null
        then
            LOGFILE_OFFLOAD="${HOME_MOUNTPOINT}/${HOME_MOUNT_SUBVOL}/.steamos/offload${LOGFILE}"
        else
            LOGFILE_OFFLOAD="${HOME_MOUNTPOINT}/.steamos/offload${LOGFILE}"
        fi
    fi
    cmd mkdir -p "$(dirname "$LOGFILE_OFFLOAD")" || true
    cmd cat "$LOGFILE" >> "$LOGFILE_OFFLOAD" || true
    cmd umount -l "$HOME_MOUNTPOINT" || true
}

exit_restore_fstab() {
    cmd mkdir -p "$ROOTFS_MOUNTPOINT"
    if ! cmd mount "$ROOTFS_DEVICE" "$ROOTFS_MOUNTPOINT"
    then
        return
    fi
    cmd btrfs property set "$ROOTFS_MOUNTPOINT" ro false || true
    fstab_files=("$ROOTFS_MOUNTPOINT/etc/fstab")
    cmd mkdir -p "$VAR_MOUNTPOINT"
    if cmd mount "$VAR_DEVICE" "$VAR_MOUNTPOINT" && [[ -f "$VAR_MOUNTPOINT/lib/overlays/etc/upper/fstab" ]]
    then
        fstab_files+=("$VAR_MOUNTPOINT/lib/overlays/etc/upper/fstab")
    fi
    cmd sed -i 's#^\S\+\s\+'"${HOME_MOUNTPOINT}"'\s\+.*$#'"${HOME_DEVICE}"' '"${HOME_MOUNTPOINT}"' ext4 defaults,nofail,x-systemd.growfs 0 2#' "${fstab_files[@]}" || true
    if mountpoint -q "$VAR_MOUNTPOINT"
    then
        cmd umount -l "$VAR_MOUNTPOINT" || true
    fi
    cmd btrfs property set "$ROOTFS_MOUNTPOINT" ro true || true
    cmd umount -l "$ROOTFS_MOUNTPOINT" || true
}

onexit=(exit_restore_fstab exit_log exit_reboot_error)
if cmd mkdir -p "$(dirname "$LOGFILE")" && cmd touch "$LOGFILE"
then
    exec &> >(tee -a "$LOGFILE")
    printf '#### %(%F %T)T ####\n'
fi
echo "(  0%) Creating sddm configuration '$SDDM_CONF_FILE'."
cmd mkdir -p "$(dirname "$SDDM_CONF_FILE")"
cat <<EOF > "$SDDM_CONF_FILE"
[Autologin]
Session=steamos-convert-home-to-btrfs.desktop
User=root
EOF
echo "(  0%) Start btrfs conversion of $HOME_MOUNTPOINT..."
systemd-notify --ready --status="Start btrfs conversion of $HOME_MOUNTPOINT..."
cmd umount -l "$HOME_DEVICE" &>/dev/null || true
# Make sure the filesystem is clean
echo "(  0%) Start filesystem check..."
if ! cmd e2fsck -fvy "$HOME_DEVICE"
then
    echo "(100%) Filesystem check error." >&2
    exit 1
fi
echo "(  5%) Filesystem check done."
# Convert to btrfs keeping label and uuid
echo "(  5%) Start btrfs conversion..."
if ! cmd btrfs-convert ${HOME_CONVERT_OPTS} "$HOME_DEVICE"
then
    echo "(100%) Btrfs conversion error." >&2
    exit 1
fi
echo "( 40%) Btrfs conversion done."
onexit=("${onexit[@]:1}")
cmd mkdir -p "$ROOTFS_MOUNTPOINT"
if ! cmd mount "$ROOTFS_DEVICE" "$ROOTFS_MOUNTPOINT"
then
    echo "(100%) Mount error." >&2
    exit 1
fi
exit_umount_rootfs() {
    cmd umount -l "$ROOTFS_MOUNTPOINT" || true
}
onexit=(exit_umount_rootfs "${onexit[@]}")
if ! cmd btrfs property set "$ROOTFS_MOUNTPOINT" ro false
then
    echo "(100%) Set readonly false error." >&2
    exit 1
fi
exit_ro_rootfs() {
    cmd btrfs property set "$ROOTFS_MOUNTPOINT" ro true || true
}
onexit=(exit_ro_rootfs "${onexit[@]}")
fstab_files=("$ROOTFS_MOUNTPOINT/etc/fstab")
cmd mkdir -p "$VAR_MOUNTPOINT"
if ! cmd mount "$VAR_DEVICE" "$VAR_MOUNTPOINT"
then
    echo "(100%) Mount error." >&2
    exit 1
fi
exit_umount_var() {
    cmd umount -l "$VAR_MOUNTPOINT" || true
}
onexit=(exit_umount_var "${onexit[@]}")
if [[ -f "$VAR_MOUNTPOINT/lib/overlays/etc/upper/fstab" ]]
then
    fstab_files+=("$VAR_MOUNTPOINT/lib/overlays/etc/upper/fstab")
fi
cmd sed -i 's#^\S\+\s\+'"${HOME_MOUNTPOINT}"'\s\+.*$#'"${HOME_DEVICE}"' '"${HOME_MOUNTPOINT}"' btrfs '"${HOME_MOUNT_OPTS}"',subvol='"${HOME_MOUNT_SUBVOL}"' 0 0#' "${fstab_files[@]}"
exit_umount_var
exit_ro_rootfs
exit_umount_rootfs
onexit=("${onexit[@]:3}")
if ! cmd mount -o "${HOME_MOUNT_OPTS}" "$HOME_DEVICE" "$HOME_MOUNTPOINT"
then
    echo "(100%) Mount error." >&2
    exit 1
fi
exit_umount_home() {
    cmd umount -l "$HOME_MOUNTPOINT" || true
}
onexit=(exit_umount_home "${onexit[@]}")
# Remove the original metadata
echo "( 40%) Remove ext2_saved."
if ! cmd btrfs subvolume delete "$HOME_MOUNTPOINT"/ext2_saved
then
    echo "(100%) Subvolume delete ext2_saved error." >&2
    exit 1
fi
# Not needed anymore
echo "( 41%) Remove lost+found."
cmd rm -rf "$HOME_MOUNTPOINT"/lost+found
# Remove the swapfile if present
echo "( 42%) Remove swapfile."
cmd rm -f "$HOME_MOUNTPOINT"/swapfile
# Create the root subvolume ${HOME_MOUNT_SUBVOL}
echo "( 43%) Create root subvolume ${HOME_MOUNT_SUBVOL}."
if ! cmd btrfs subvolume create "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL"
then
    echo "(100%) Subvolume creation error." >&2
    exit 1
fi
# Move all existing files into the new root
echo "( 44%) Move all files into ${HOME_MOUNT_SUBVOL}..."
if ! cmd find "$HOME_MOUNTPOINT" -mindepth 1 -maxdepth 1 -not -name "$HOME_MOUNT_SUBVOL" -exec mv -t "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL" '{}' +
then
    echo "(100%) Move all files into ${HOME_MOUNT_SUBVOL} error." >&2
    exit 1
fi
echo "( 50%) Moving all files into ${HOME_MOUNT_SUBVOL} done."
# Pass all files through the allocator, can take a while
nbfiles="$(find "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL" -type f -printf '\n' | wc -l)"
echo "( 50%) Start defragmentation on $nbfiles files..."
if ! cmd stdbuf -oL btrfs filesystem defrag -czstd -v -r -f "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL" | awk '{printf("( %d%%) Defragmenting %s\n",50+(NR/'"$nbfiles"'*40),$0)}'
then
    echo "(100%) Defragmentation error." >&2
    exit 1
fi
echo "( 90%) Defragmentation done."
# Run balance
echo "( 90%) Start balance..."
if ! cmd btrfs balance start -m -v "$HOME_MOUNTPOINT"
then
    echo "(100%) Balance error." >&2
    exit 1
fi
echo "(100%) Balance done."
echo "(100%) Set up Steam's 'downloading' and 'temp' folders as btrfs subvolumes and disable COW..."
for d in "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL"/deck/.local/share/Steam/steamapps/{downloading,temp}
do
    if ! btrfs subvolume show "$d" &>/dev/null; then
        cmd mkdir -p "$d"
        cmd rm -rf "$d"
        cmd btrfs subvolume create "$d"
        cmd chattr +C "$d"
        cmd chown -R deck:deck "$HOME_MOUNTPOINT/$HOME_MOUNT_SUBVOL"/deck
    fi
done
echo "(100%) Set up Steam's 'downloading' and 'temp' folders as btrfs subvolumes and disable COW done."
exit_umount_home
onexit=("${onexit[@]:1}")
echo "(100%) Btrfs conversion of $HOME_MOUNTPOINT done."
echo "(100%) Removing sddm configuration '$SDDM_CONF_FILE'."
clear_sddm_conf
mask_service
echo "(100%) Persisting log."
exit_log
onexit=()
systemd-notify --status="Btrfs conversion of $HOME_MOUNTPOINT done."
echo "(100%) Rebooting in 4 seconds..."
sleep 4
cmd systemctl reboot
