#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: et sts=4 sw=4

set -eu

progress() {
    if plymouth --ping 2>/dev/null
    then
        plymouth system-update --progress "$1"
    fi
    echo "$1%"
}

while [[ "$#" -ne 0 ]]
do
    if [[ "$1" =~ ^(-h|--help)$ ]]
    then
        echo "Usage: ${0##*/} [-h|--help] [--debug]"
        exit 0
    elif [[ "$1" == "--debug" ]]
    then
        debug=true
    else
        echo "$1: Invalid argument" >&2
        exit 1
    fi
    shift
done

lastperc="-1"
while read -r line
do
    # Empty line: skip it!
    if [[ "${#line}" -eq 0 ]]
    then
        continue
    fi
    
    # Print the journal to stderr
    if [[ "${debug:-}" ]]
    then
        echo "$line" >&2
    fi
    
    if [[ $line =~ ^\(\ *[0-9]+%\) ]]
    then
        perc="${line#"${line%%[!\([:space:]]*}"}"
        perc="${perc%\%\)*}"
        msg="${line#\(*\) }"
        if [[ "$perc" -ne "$lastperc" ]]
        then
            if [[ "$perc" -eq 0 ]]
            then
                if plymouth --ping 2>/dev/null
                then
                    plymouth change-mode --system-upgrade
                    plymouth display-message --text="$msg"
                fi
                progress "$perc"
            elif [[ "$perc" -eq 100 ]]
            then
                progress "$perc"
                if plymouth --ping 2>/dev/null
                then
                    plymouth change-mode --boot-up
                    plymouth display-message --text="$msg"
                fi
            else
                progress "$perc"
                if ! [[ $msg =~ ^Defragmenting ]] && plymouth --ping 2>/dev/null
                then
                    plymouth display-message --text="$msg"
                fi
            fi
        elif ! [[ $msg =~ ^Defragmenting ]] && plymouth --ping 2>/dev/null
        then
            plymouth display-message --text="$msg"
        fi
        lastperc="$perc"
    fi
done < <(journalctl --unit steamos-convert-home-to-btrfs.service --follow --output cat)
